### ISSUE TITLE
Problem 06-unions, backdoor

### ISSUE THREAD

**Issue by Shemrock3267** [total-typescript/beginners-typescript-tutorial#21]
Hey @mattpocock .
Thanks for your effort and time spent on this course.
I just want to point out that you can *fool* typechecker in this exercise with simply typing this, and it will pass the test.
`role: string[]` instead of `role: 'admin' | 'user' | 'super-admin'`

**Comment by mattpocock** [comment]
Thanks!

I'm not too interested on making every exercise _exactly_ bulletproof. As I've said in other issues, the exercises will be accompanied by videos which make the intent of each problem/solution clear.
