### ISSUE TITLE
The solution for exercise three does not test a simple case 

### ISSUE THREAD

**Issue by eg180** [total-typescript/beginners-typescript-tutorial#38]
This seems so simple that maybe I'm overthinking it and wrong? Either way, I'm not sure why we don't test the case that it works with just the last name as well.

**Comment by mattpocock** [comment]
I'm confused by what you mean. It shouldn't work with just the last name: it needs the first name.

**Comment by eg180** [comment]
Ahhh okay - I saw 'optional properties' (plural) and automatically assumed it meant both should be optional. Anyway - thanks for these exercises, Matt. Cheers.
