### ISSUE TITLE
@types/react-dom can't find exported member.

### ISSUE THREAD

**Issue by Gustafssonz** [total-typescript/beginners-typescript-tutorial#41]
Hey! 
Superconfusing error I get when I download the project and install it. When running the install and then an exercise I get this message:

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/22516790/190911402-3b408ea5-ff0a-493e-8dfd-40fa012b194a.png">

../../../../node_modules/@types/react-dom/index.d.ts:20:19 - error TS2724: '"react"' has no exported member named 'SFCElement'. Did you mean 'CElement'

But I can't even find the @types/react-dom/index.d.ts file.

**Comment by mattpocock** [comment]
This doesn't look like an issue to do with our repo - it looks like a local-only bug. You notice how the node_modules it's referencing are outside the repo?
