### ISSUE TITLE
Can not install packages and run project

### ISSUE THREAD

**Issue by reza-salemi** [total-typescript/beginners-typescript-tutorial#50]
I have cloned the project and tried to install packages. But I got the following error:

error F:\code\beginners-typescript-tutorial\node_modules\esbuild: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: F:\code\beginners-typescript-tutorial\node_modules\esbuild
Output:
node:internal/errors:841
  const err = new Error(message);

**Comment by darklight9811** [comment]
@reza-salemi what node version you are using?

**Comment by mattpocock** [comment]
I find it strange that node_modules/esbuild would be erroring, since that isn't a dependency of this project.

**Comment by darklight9811** [comment]
@mattpocock isn't it an indirect dependency of a package you use?

**Comment by reza-salemi** [comment]
@darklight9811 
I have node version 18.8.0
Also, 16.15.0

**Comment by mattpocock** [comment]
@darklight9811 You're correct actually, it is part of vitest.

@reza-salemi Could you try installing again with latest, which now uses npm.

**Comment by mattpocock** [comment]
I'm also going to close this issue - the primary purpose of this repo is to facilitate https://www.totaltypescript.com/tutorials/beginners-typescript, so I don't necessarily want to have open issues about installation problems.

**Comment by darklight9811** [comment]
@reza-salemi try to open or create a repo that uses vitest, if the issue persists, create an issue on their repo or esbuild's
