### ISSUE TITLE
Add a preferred node version

### ISSUE THREAD

**Issue by luischoma** [total-typescript/beginners-typescript-tutorial#70]
Hey!!

First of, thanks for the great and very useful initiative!

I would like to suggest adding a `.nvmrc` file to the project. The reason is that, on my case, I have an older node version installed and used by default. When trying to run the first exercise I would get this error:
```
  argv.passWithNoTests ?? (argv.passWithNoTests = true);
                        ^
SyntaxError: Unexpected token '?'
```

This is related to vite configs I guess, but since installing dependencies didn't throw any error took me a few minutes to realize it was the node version. Adding the preferred node version to the project would help to identify this earlier.

:)

**Comment by WikiRik** [comment]
I believe all [currently supported versions of Node](https://github.com/nodejs/release#release-schedule) should work, but considering that the installed version of `@types/node` is `^18.6.5` the recommended Node version to use would be 18.x

**Comment by mattpocock** [comment]
Hey! I think an LTS version of Node is a safe assumption for a project to make without needing to do anything our side.
